type: TunableUNet
in_channels: 1
out_classes: 1
# Options: either 'single' or 'double'
conv_block: double
# Model depth
depth: 2
# Options: 1 to n (2**n)
filters: 3
# Options: 1 (no dilation), 2, 3, 4
dilation: 1
batch_norm: True
# Options: in the range of 0.1, 0.9
dropout: 0
# Options: 'upconv', 'upsample'
up_mode: upconv
attention: False
relu: True
# Options: 'normal', 'xavier', 'HeNormal', 'HeUniform', 'orthogonal'
weight_init: HeNormal 
